spring:
  datasource:
    url: jdbc:h2:mem:linkshortener;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    hikari:
      minimumIdle: 1
      maximum-pool-size: 5
      maxLifetime: 300000
      idle-timeout: 10000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        jdbc:
          time_zone: UTC
          batch_size: 15
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          fail_on_pagination_over_collection_fetch: true
  h2:
    console:
      enabled: false

app:
  base-url: http://localhost:8080

security:
  jwt:
    access-token:
      validity: 900000 # 15 minutes (in ms)
      cookie:
        name: 792F423F4528482B
        validity: 604800 # 7 days (in seconds)
    refresh-token:
      validity: 604800000 # 7 days (in ms)
      cookie:
        name: 566B597033733676
        validity: 604800 # 7 days (in seconds)
    secret: 2F423F4528482B4D6251655468566D597133743677397A24432646294A404E6